# Generated by Django 4.1.2 on 2022-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
